/**
 * Property 63 — Campaign metadata validation
 *
 * Proves that `validateCampaignMetadata` correctly accepts or rejects inputs
 * across the full space of possible metadata strings.
 *
 * Generators cover:
 *   - Valid JSON objects (arbitrary depth / keys / values)
 *   - Invalid JSON (random strings that are not parseable)
 *   - JSON non-objects at root (arrays, strings, numbers, booleans, null literal)
 *   - null / undefined (always valid — field is optional)
 *   - Oversized payloads (byte length > CAMPAIGN_METADATA_MAX_BYTES)
 *   - Multi-byte Unicode strings (emoji, CJK, RTL characters)
 *   - Empty string (not valid JSON)
 *   - Boundary values: exactly at and one byte over the size limit
 *
 * Edge cases called out inline with comments.
 *
 * Assumptions:
 *   - The DB column is TEXT (unbounded); size enforcement is the service layer's job.
 *   - Callers JSON.stringify before passing to the parser; we validate the string form.
 *
 * Follow-up work:
 *   - Once campaign types stabilise, add a key-allowlist property per type.
 *   - Consider a max-nesting-depth invariant to guard against stack-overflow via
 *     deeply recursive JSON.parse.
 */

import { describe, it, expect } from "vitest";
import * as fc from "fast-check";
import {
  validateCampaignMetadata,
  CAMPAIGN_METADATA_MAX_BYTES,
} from "@/lib/validation/validator";

// ---------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------

/**
 * Produces a JSON-serialised plain object with arbitrary keys and leaf values.
 * fast-check's `fc.object()` generates nested structures; we serialise to string
 * to match the shape the service layer receives.
 */
const validMetadataString = () =>
  fc
    .object({ maxDepth: 4, key: fc.string({ minLength: 1, maxLength: 32 }) })
    .map((obj) => JSON.stringify(obj))
    // Guard: serialised form must fit within the size limit.
    // Objects generated by fc.object() are small, but the filter makes the
    // invariant explicit and keeps the generator honest.
    .filter(
      (s) => Buffer.byteLength(s, "utf8") <= CAMPAIGN_METADATA_MAX_BYTES
    );

/**
 * Produces strings that are NOT valid JSON at all (random printable text).
 * We filter out anything that happens to be parseable so the generator is pure.
 */
const invalidJsonString = () =>
  fc
    .string({ minLength: 1, maxLength: 512 })
    .filter((s) => {
      try {
        JSON.parse(s);
        return false; // accidentally valid JSON — skip
      } catch {
        return true;
      }
    });

/**
 * Produces valid JSON whose root value is NOT a plain object:
 * arrays, strings, numbers, booleans, and the JSON null literal.
 *
 * Edge case: JSON.parse('null') returns the JS null value, which our validator
 * must reject because the *string* "null" is not a valid metadata payload even
 * though the *JS value* null is (the field being absent).
 */
const nonObjectJsonString = () =>
  fc.oneof(
    // JSON array
    fc.array(fc.integer()).map((a) => JSON.stringify(a)),
    // JSON string
    fc.string().map((s) => JSON.stringify(s)),
    // JSON number
    fc.float().map((n) => JSON.stringify(n)),
    // JSON boolean
    fc.boolean().map((b) => JSON.stringify(b)),
    // JSON null literal — distinct from JS null (which is "field absent")
    fc.constant("null")
  );

/**
 * Produces a string that is a valid JSON object but whose UTF-8 byte length
 * exceeds CAMPAIGN_METADATA_MAX_BYTES.
 *
 * We build a minimal wrapper object and pad a single key's value to push it
 * over the limit. Using ASCII 'a' keeps byte-count == char-count predictable.
 */
const oversizedMetadataString = () => {
  // Overhead: '{"k":"' + '"}'  = 7 bytes
  const overhead = 7;
  const padLength = CAMPAIGN_METADATA_MAX_BYTES - overhead + 1; // one byte over
  return fc.constant(JSON.stringify({ k: "a".repeat(padLength) }));
};

/**
 * Produces a valid JSON object string that contains multi-byte Unicode
 * characters (emoji, CJK, etc.).  Verifies that byte-length counting is
 * correct and that valid Unicode objects are accepted when within limits.
 */
const unicodeMetadataString = () =>
  fc
    .record({
      label: fc.string({ minLength: 1, maxLength: 50 }),
      // emoji range U+1F600–U+1F64F (4 bytes each in UTF-8)
      icon: fc.constantFrom("🚀", "🌕", "💎", "🔥", "⚡"),
    })
    .map((obj) => JSON.stringify(obj))
    .filter(
      (s) => Buffer.byteLength(s, "utf8") <= CAMPAIGN_METADATA_MAX_BYTES
    );

// ---------------------------------------------------------------------------
// Property 63 — suite
// ---------------------------------------------------------------------------

describe("Property 63 — campaign metadata validation", () => {
  // -------------------------------------------------------------------------
  // Valid inputs
  // -------------------------------------------------------------------------

  it("accepts null (field is optional)", () => {
    // Not a property loop — null is a single deterministic value.
    expect(validateCampaignMetadata(null).valid).toBe(true);
  });

  it("accepts undefined (field is optional)", () => {
    expect(validateCampaignMetadata(undefined).valid).toBe(true);
  });

  it("accepts valid JSON object strings — 100 iterations", () => {
    // @property 63
    fc.assert(
      fc.property(validMetadataString(), (metadata) => {
        const result = validateCampaignMetadata(metadata);
        expect(result.valid).toBe(true);
        expect(result.error).toBeUndefined();
      }),
      { numRuns: 100, verbose: true }
    );
  });

  it("accepts valid JSON objects with Unicode content — 100 iterations", () => {
    // @property 63 — multi-byte Unicode edge case
    fc.assert(
      fc.property(unicodeMetadataString(), (metadata) => {
        const result = validateCampaignMetadata(metadata);
        expect(result.valid).toBe(true);
      }),
      { numRuns: 100, verbose: true }
    );
  });

  it("accepts an empty JSON object '{}'", () => {
    // Edge case: minimal valid payload
    expect(validateCampaignMetadata("{}").valid).toBe(true);
  });

  it("accepts a JSON object at exactly the byte limit", () => {
    // Boundary: exactly CAMPAIGN_METADATA_MAX_BYTES bytes must be accepted.
    // Build the largest possible value that fits.
    const overhead = 7; // '{"k":"' + '"}'
    const padLength = CAMPAIGN_METADATA_MAX_BYTES - overhead;
    const atLimit = JSON.stringify({ k: "a".repeat(padLength) });
    expect(Buffer.byteLength(atLimit, "utf8")).toBe(CAMPAIGN_METADATA_MAX_BYTES);
    expect(validateCampaignMetadata(atLimit).valid).toBe(true);
  });

  // -------------------------------------------------------------------------
  // Invalid inputs — must be rejected
  // -------------------------------------------------------------------------

  it("rejects invalid JSON strings — 100 iterations", () => {
    // @property 63
    fc.assert(
      fc.property(invalidJsonString(), (metadata) => {
        const result = validateCampaignMetadata(metadata);
        expect(result.valid).toBe(false);
        expect(result.error).toMatch(/valid JSON/i);
      }),
      { numRuns: 100, verbose: true }
    );
  });

  it("rejects JSON non-objects at root (arrays, primitives, null literal) — 100 iterations", () => {
    // @property 63 — root-type guard
    fc.assert(
      fc.property(nonObjectJsonString(), (metadata) => {
        const result = validateCampaignMetadata(metadata);
        expect(result.valid).toBe(false);
        // Could be "not an object" or "null literal" — both are rejections
        expect(result.error).toBeDefined();
      }),
      { numRuns: 100, verbose: true }
    );
  });

  it("rejects oversized metadata — 100 iterations", () => {
    // @property 63 — size limit enforcement
    fc.assert(
      fc.property(oversizedMetadataString(), (metadata) => {
        expect(Buffer.byteLength(metadata, "utf8")).toBeGreaterThan(
          CAMPAIGN_METADATA_MAX_BYTES
        );
        const result = validateCampaignMetadata(metadata);
        expect(result.valid).toBe(false);
        expect(result.error).toMatch(/exceeds maximum size/i);
      }),
      { numRuns: 100, verbose: true }
    );
  });

  it("rejects a payload one byte over the size limit", () => {
    // Boundary: CAMPAIGN_METADATA_MAX_BYTES + 1 must be rejected.
    const overhead = 7;
    const padLength = CAMPAIGN_METADATA_MAX_BYTES - overhead + 1;
    const oneOver = JSON.stringify({ k: "a".repeat(padLength) });
    expect(Buffer.byteLength(oneOver, "utf8")).toBe(
      CAMPAIGN_METADATA_MAX_BYTES + 1
    );
    const result = validateCampaignMetadata(oneOver);
    expect(result.valid).toBe(false);
    expect(result.error).toMatch(/exceeds maximum size/i);
  });

  it("rejects an empty string (not valid JSON)", () => {
    // Edge case: empty string is not parseable
    const result = validateCampaignMetadata("");
    expect(result.valid).toBe(false);
    expect(result.error).toMatch(/valid JSON/i);
  });

  it("rejects non-string, non-null values (number, boolean, object)", () => {
    // Edge case: callers must serialise before passing
    for (const bad of [42, true, { key: "value" }, []]) {
      const result = validateCampaignMetadata(bad);
      expect(result.valid).toBe(false);
      expect(result.error).toMatch(/string or null/i);
    }
  });

  // -------------------------------------------------------------------------
  // Round-trip invariant
  // -------------------------------------------------------------------------

  it("round-trip: JSON.stringify(obj) is always accepted — 100 iterations", () => {
    /**
     * Invariant: for any plain object that fits within the size limit,
     * JSON.stringify(obj) must pass validation.
     * This mirrors the real call-site pattern in the event parser.
     */
    fc.assert(
      fc.property(
        fc
          .object({ maxDepth: 3, key: fc.string({ minLength: 1, maxLength: 16 }) })
          .filter(
            (obj) =>
              Buffer.byteLength(JSON.stringify(obj), "utf8") <=
              CAMPAIGN_METADATA_MAX_BYTES
          ),
        (obj) => {
          const serialised = JSON.stringify(obj);
          const result = validateCampaignMetadata(serialised);
          expect(result.valid).toBe(true);
        }
      ),
      { numRuns: 100, verbose: true }
    );
  });
});
